### ISSUE TITLE
Exec format error when trying to install on Linux via Linuxbrew

### ISSUE THREAD

**Issue by SenseiMarv** [mike-engel/homebrew-jwt-cli#1]
### Summary

Brew will download the macOS binaries when trying to install jwt-cli on Linux via Linuxbrew. Running `jwt` then results in `Exec format error`.

### Steps to reproduce

Using Ubuntu 20.04.2 LTS.

1. [Install Linuxbrew](https://docs.brew.sh/Homebrew-on-Linux#install)
2. `brew tap mike-engel/jwt-cli`
3. `brew install jwt-cli`
4. `jwt`

### Expected behavior

jwt-cli runs.

### Actual behavior

`Exec format error`

### Hints

As seen in the following shell output, brew downloads the macOS files even though I am on a Linux system:

```shell
❯ brew install jwt-cli
==> Installing jwt-cli from mike-engel/jwt-cli
==> Downloading https://github.com/mike-engel/jwt-cli/releases/download/4.0.0/jwt-macOS.tar.gz
```

**Comment by mike-engel** [comment]
@SenseiMarv Thanks for this! Do you know of other casks that work on both macos an linux?

**Comment by SenseiMarv** [comment]
~Recently I used this formula and it's implementation worked flawlessly: https://github.com/tclass/homebrew-cloud_sql_proxy/blob/master/cloud_sql_proxy.rb~

I looked at the formula linked above and realized that they obviously built the application during installation, which contradicts your approach. So I came up with another solution:
You could use the output of the `RUBY_PLATFORM` parameter to find out the OS. I wrote the following example that uses this approach:

```ruby
def os
  case RUBY_PLATFORM
  when /darwin/
    "macOS"
  when /linux/
    "linux"
  else
    "windows"
  end
end

class JwtCli < Formula
  desc "Super fast CLI tool to decode and encode JWTs built in Rust"
  homepage "https://github.com/mike-engel/jwt-cli"
  version "4.0.0"
  url "https://github.com/mike-engel/jwt-cli/releases/download/#{version}/jwt-#{os}.tar.gz"
  sha256 "a58929cba03d3639b29281508b638f7da3317a86ef1f6da9290107a7f97ae157"
  head "https://github.com/mike-engel/jwt-cli.git"

  def install
    libexec.install Dir["*"]
    bin.install_symlink "#{libexec}/jwt" => "jwt"
  end

  test do
    system bin/"jwt", "encode", "-S", "secret"
  end
end
```

Please note that I have never used Ruby, so I am sorry if this approach is not practical 😅

This example would also need to be tested, as I have not done that yet.

**Comment by mike-engel** [comment]
Thanks @SenseiMarv! Homebrew also provides `os_macos` and `os_linux` helpers, so I'll be testing those as well. I can't promise a timeline, but hopefully soon 😄
